### ISSUE TITLE
[Bug]: wluma writing "1" to /sys/class/backlight/intel_backlight/brightness *really* fast while laptop lid is closed

### ISSUE THREAD

**Issue by kelvie** [maximbaz/wluma#56]
### Steps for reproducing the issue

Run wluma with this config:

```toml
[als.iio]
path = "/sys/bus/iio/devices"
thresholds = { 0 = "night", 20 = "dark", 80 = "dim", 250 = "normal", 500 = "bright", 800 = "outdoors" }

# [als.webcam]
# video = 0
# thresholds = { 0 = "night", 15 = "dark", 30 = "dim", 45 = "normal", 60 = "bright", 75 = "outdoors" }

# [als.time]
# thresholds = { 0 = "night", 7 = "dark", 9 = "dim", 11 = "normal", 13 = "bright", 16 = "normal", 18 = "dark", 20 = "night" }

# [als.none]

[[output.backlight]]
name = "eDP-1"
path = "/sys/class/backlight/intel_backlight"
capturer = "none"
```
Then close the laptop lid.

### What is the buggy behavior?

I remember doing an strace and it kept writing "1" to /sys/class/backlight/intel_backlight/brightness

To the point that `systemd-udevd` was using 100% CPU and a `udevadm monitor` would spam the console with brightness changes

### What is the expected behavior?

That it set it to `1` once, and leave it there.

### Logs

```shell
No logs when seting RUST_LOG=debug


> cat ~/.local/share/wluma/eDP-1.yaml
---
output_name: eDP-1
entries:
  - lux: dark
    luma: 0
    brightness: 10561
  - lux: night
    luma: 0
    brightness: 1
  - lux: normal
    luma: 0
    brightness: 22081
```
```


### Version

4.1.2.r1.g0c49755-1

### Environment

```shell
lsb_release -a; uname -a; pgrep -l sway; pacman -Q | egrep "(wlroots|vulkan|sway|clang|rust)";


LSB Version:    n/a
Distributor ID: Arch
Description:    Arch Linux
Release:        rolling
Codename:       n/a
Linux kelvie-fw 5.19.10-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 20 Sep 2022 15:17:59 +0000 x86_64 GNU/Linux
egrep: warning: egrep is obsolescent; using grep -E
clang 14.0.6-2
rust 1:1.63.0-1
rust-analyzer 20220919-1
rust-src 1:1.63.0-1
vulkan-icd-loader 1.3.226-1
vulkan-tools 1.3.226-1
```
```
